eca_float_or_token:
  label: 'Float or Token'
  class: '\Drupal\eca\Plugin\DataType\FloatOrToken'
  definition_class: '\Drupal\eca\TypedData\FloatOrTokenDataDefinition'
eca_integer_or_token:
  label: 'Integer or Token'
  class: '\Drupal\eca\Plugin\DataType\IntegerOrToken'
  definition_class: '\Drupal\eca\TypedData\IntegerOrTokenDataDefinition'
