<?php

/**
 * @file
 * Drupal Webprofiler.
 */

declare(strict_types=1);

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\webprofiler\Hook\WebprofilerHooks;

/**
 * Implements hook_theme().
 */
#[LegacyHook]
function webprofiler_theme(): array {
  return \Drupal::service(WebprofilerHooks::class)->theme();
}

/**
 * Implements hook_cache_flush().
 */
#[LegacyHook]
function webprofiler_cache_flush(): void {
  \Drupal::service(WebprofilerHooks::class)->cacheFlush();
}
