<?php

namespace Drupal\eca_development;

use Drupal\Component\Plugin\Exception\PluginException;
use Drupal\Component\Serialization\Yaml;
use Drupal\eca\Entity\Eca;
use Drupal\modeler_api\Form\Settings;
use Drupal\modeler_api\Plugin\ModelerApiModeler\ModelerInterface;
use Drupal\modeler_api\Plugin\ModelerApiModelOwner\ModelOwnerInterface;
use Drupal\modeler_api\Plugin\ModelerPluginManager;

/**
 * Prepares portable ECA library model artifacts.
 */
final class LibraryModelArtifacts {

  /**
   * The provider key of Modeler API's third-party settings on a model.
   *
   * @see \Drupal\modeler_api\Plugin\ModelerApiModelOwner\ModelOwnerBase::setThirdPartySetting()
   */
  private const string THIRD_PARTY_PROVIDER = 'modeler_api';

  /**
   * The config name prefix of separately stored raw model data.
   */
  private const string DATA_MODEL_PREFIX = 'modeler_api.data_model.';

  /**
   * The plugin ID of the modeler that renders every published library graph.
   *
   * Fixed on purpose: which modeler authored a model says nothing about how
   * the library page should draw it.
   */
  private const string GRAPH_MODELER_ID = 'workflow_modeler';

  /**
   * The raw file format the published graph has to be in.
   *
   * The standalone viewer loads a ".json" sibling of the page, so a modeler
   * producing anything else has nothing to contribute here.
   */
  private const string GRAPH_FILE_EXTENSION = 'json';

  public function __construct(
    private readonly ?ModelerPluginManager $modelerPluginManager,
  ) {}

  /**
   * Determines whether a model should be published.
   */
  public function isExportable(Eca $eca): bool {
    return $eca->status();
  }

  /**
   * Serializes portable model configuration for publication.
   *
   * A published model is modeler agnostic, and three keys of Modeler API's
   * third-party settings claim otherwise, so all three are rewritten:
   *
   * - "data" is the raw modeler graph. It is published beside this file as its
   *   own artifact, which is the copy the viewer loads, so carrying it inline
   *   as well ships the same graph twice and lets the two copies disagree with
   *   no way for a reader to tell which one the page uses.
   * - "modeler_id" names the modeler that authored the model, which is not the
   *   modeler that produced the sibling graph: that one is generated by a fixed
   *   Workflow Modeler no matter what the model says. Publishing the key would
   *   advertise a modeler that did not produce its own neighbor, and would hand
   *   an importing site a model bound to a modeler whose diagram it never got.
   * - "storage" is forced to "none", so that a re-save on the consuming site
   *   cannot reinstate a payload this artifact never carried.
   *
   * Everything else in the map is portable model metadata and is preserved,
   * most notably the label, which Eca::label() reads and which is therefore
   * the model's only human-readable name.
   *
   * Recipe export applies the same rule, so both publication paths hand out
   * the same model.
   *
   * @see \Drupal\eca\Entity\Eca::label()
   * @see \Drupal\modeler_api\ExportRecipe
   */
  public function config(Eca $eca): string {
    $config = $eca->toArray();
    unset($config['uuid'], $config['_core']);
    $settings = $config['third_party_settings'][self::THIRD_PARTY_PROVIDER] ?? NULL;
    if (is_array($settings)) {
      unset($settings['data'], $settings['modeler_id']);
      // Forcing the storage method puts a key back where the two removals took
      // keys out, so a map that held nothing else cannot end up as a
      // "modeler_api: {  }" that reads as truncation to somebody copying this
      // configuration by hand.
      $settings['storage'] = Settings::STORAGE_OPTION_NONE;
      $config['third_party_settings'][self::THIRD_PARTY_PROVIDER] = $settings;
    }
    $this->dropDataModelDependency($config);
    return Yaml::encode($config);
  }

  /**
   * Removes the dependency on separately stored raw model data.
   *
   * A model using the "separate" storage method keeps its graph in its own
   * config entity and depends on it. That entity is not published here, for
   * the same reason the inline graph is dropped, so leaving the dependency
   * behind would name a config object the importing site cannot resolve.
   *
   * @param array $config
   *   The model configuration, modified in place.
   */
  private function dropDataModelDependency(array &$config): void {
    $dependencies = $config['dependencies']['config'] ?? NULL;
    if (!is_array($dependencies)) {
      return;
    }
    // Config dependencies are a sequence, so the survivors have to be
    // renumbered from zero or the removal turns the list into a keyed map.
    $remaining = array_values(array_filter(
      $dependencies,
      static fn (mixed $name): bool => !is_string($name) || !str_starts_with($name, self::DATA_MODEL_PREFIX),
    ));
    if (count($remaining) === count($dependencies)) {
      return;
    }
    if ($remaining !== []) {
      $config['dependencies']['config'] = $remaining;
      return;
    }
    // An empty "config: {  }" reads as truncation just like an emptied
    // settings map, so the keys the removal emptied go with it.
    unset($config['dependencies']['config']);
    if ($config['dependencies'] === []) {
      unset($config['dependencies']);
    }
  }

  /**
   * Exports the model's library graph when the fixed modeler is available.
   *
   * The graph is asked of self::GRAPH_MODELER_ID rather than of the modeler
   * the model names, because it is a rendering concern of the library page
   * and not a property of how the model was authored. A published library
   * model is deliberately modeler agnostic and therefore carries no
   * "modeler_id" at all, so asking the model would only ever reach Modeler
   * API's substituted "fallback" plugin, which declares no raw format and
   * exports nothing. The Workflow Modeler instead rebuilds the graph from the
   * model entity, so it needs no stored payload and no authoring modeler.
   *
   * @see \Drupal\modeler_api\Plugin\ModelerApiModelOwner\ModelOwnerBase::getModelerId()
   */
  public function graph(Eca $eca, ModelOwnerInterface $owner): ?string {
    $modeler = $this->graphModeler();
    if ($modeler === NULL) {
      return NULL;
    }
    $graph = $modeler->export($owner, $eca);
    return $graph !== NULL && $graph !== '' ? $graph : NULL;
  }

  /**
   * Resolves the fixed modeler that renders published library graphs.
   *
   * Modeler API and the Workflow Modeler are versioned independently of ECA,
   * and the modeler ships in a project of its own, so a publishing site may
   * legitimately have neither. Both cases publish no graph instead of failing
   * the documentation export. Checking the resolved plugin's raw format also
   * rejects the "fallback" plugin that Modeler API substitutes when the
   * Workflow Modeler is not installed.
   *
   * @return \Drupal\modeler_api\Plugin\ModelerApiModeler\ModelerInterface|null
   *   The modeler, or NULL when this site cannot produce a library graph.
   */
  private function graphModeler(): ?ModelerInterface {
    if ($this->modelerPluginManager === NULL) {
      return NULL;
    }
    try {
      $modeler = $this->modelerPluginManager->createInstance(self::GRAPH_MODELER_ID);
    }
    catch (PluginException) {
      return NULL;
    }
    if (!$modeler instanceof ModelerInterface || $modeler->getRawFileExtension() !== self::GRAPH_FILE_EXTENSION) {
      return NULL;
    }
    return $modeler;
  }

}
